<<<<<<< HEAD
# Generated by Django 3.2.13 on 2022-10-07 00:55
=======
# Generated by Django 3.2.13 on 2022-09-02 05:00
>>>>>>> d91e101d9b9fccd0ec02132f6b839b5d2dcb06bf

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('audience', models.IntegerField()),
<<<<<<< HEAD
                ('release_date', models.DateTimeField(auto_now_add=True)),
=======
                ('release_data', models.DateField()),
>>>>>>> d91e101d9b9fccd0ec02132f6b839b5d2dcb06bf
                ('genre', models.CharField(max_length=30)),
                ('score', models.FloatField()),
                ('poster_url', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
